// Generated by CoffeeScript 1.6.1
(function() {

  chrome.extension.onConnect.addListener(function(port) {
    port.onMessage.addListener(function(message) {
      return chrome.tabs.query({
        currentWindow: true,
        active: true
      }, function(tabs) {
        return chrome.tabs.sendMessage(tabs[0].id, message);
      });
    });
    return chrome.extension.onMessage.addListener(function(message, sender) {
      return port.postMessage(message);
    });
  });

}).call(this);
