// Generated by CoffeeScript 1.6.1
(function() {

  chrome.extension.onConnect.addListener(function(port) {
    port.onMessage.addListener(function(message) {
      switch (message.label) {
        case 'retrieve_state':
          return chrome.storage.sync.get(null, function(data) {
            return port.postMessage(data);
          });
        case 'save_state':
          return chrome.storage.sync.set({
            color: message.data.color,
            recentColors: message.data.recentColors
          });
        case 'open_contribute':
          return chrome.tabs.create({
            url: message.data.url
          });
        default:
          return chrome.tabs.query({
            currentWindow: true,
            active: true
          }, function(tabs) {
            return chrome.tabs.sendMessage(tabs[0].id, message);
          });
      }
    });
    return chrome.extension.onMessage.addListener(function(message, sender) {
      return port.postMessage(message);
    });
  });

}).call(this);
