// Generated by CoffeeScript 1.6.1
(function() {
  var model, port;

  model = new Backbone.Model({
    color: '#4573D5',
    steps: 40,
    blendColor: '#D54545',
    sitePalette: ['#CCC']
  });

  if (chrome.runtime != null) {
    port = chrome.runtime.connect();
    port.postMessage("Request Tab Data");
    port.onMessage.addListener(function(msg) {
      return model.set({
        sitePalette: msg
      });
    });
  }

  $(function() {
    var colorView, sitePaletteView, tabView;
    colorView = new Panel.Views.ColorView({
      model: model
    });
    $('.side').html(colorView.render().el);
    sitePaletteView = new Panel.Views.SitePaletteView({
      model: model
    });
    $('.side').prepend(sitePaletteView.render().el);
    tabView = new Panel.Views.TabView({
      model: model
    });
    tabView.on('selection', function(selection) {
      var view;
      view = (function() {
        switch (selection) {
          case 'schemas':
            return new Panel.Views.SchemaView({
              model: this.model
            });
          case 'blend':
            return new Panel.Views.BlendView({
              model: this.model
            });
          default:
            return new Panel.Views.RangeView({
              model: this.model,
              mode: selection
            });
        }
      }).call(this);
      return this.update(view.render().el);
    }, tabView);
    return $('.main').html(tabView.render().el);
  });

}).call(this);
