// Generated by CoffeeScript 1.6.1
(function() {
  var model, port, recentColors;

  model = new Backbone.Model({
    color: '#4573D5',
    rangeStart: '#4573D5',
    steps: 40,
    blendColor: '#D54545',
    palette: [],
    copyFormat: 'hex',
    tab: 'lighten',
    pageColorsCollapsed: false
  });

  recentColors = new Backbone.Collection;

  model.on('change:color', function() {
    var color;
    recentColors.add(new Backbone.Model({
      color: model.get('color')
    }));
    if (model.get('syncColor')) {
      if (chrome.runtime != null) {
        color = model.get('syncColor');
        return chrome.runtime.connect().postMessage({
          label: 'sync',
          color: [Panel.Lib.Color.toHexCSS(color), Panel.Lib.Color.toRgbCSS(color), Panel.Lib.Color.toHslCSS(color)],
          newColor: model.get('color')
        });
      }
    }
  });

  model.on('change:syncColor', function() {
    var color;
    if ((chrome.runtime != null) && model.get('syncColor')) {
      color = model.get('syncColor');
      return chrome.runtime.connect().postMessage({
        label: 'color_to_sync_selected',
        color: [Panel.Lib.Color.toHexCSS(color), Panel.Lib.Color.toRgbCSS(color), Panel.Lib.Color.toHslCSS(color)]
      });
    }
  });

  if (chrome.runtime != null) {
    port = chrome.runtime.connect();
    port.postMessage({
      label: 'retrieve_state'
    });
    port.onMessage.addListener(function(data) {
      model.set(data.color);
      return recentColors.reset(data.recentColors);
    });
    model.on('change', function() {
      return port.postMessage({
        label: 'save_state',
        data: {
          color: model.toJSON(),
          recentColors: recentColors.toJSON().splice(0, 20)
        }
      });
    });
  }

  $(function() {
    var colorControlsView, colorView, paletteView, recentColorsView, tabView;
    colorView = new Panel.Views.ColorView({
      model: model
    });
    $('.side').html(colorView.render().el);
    colorControlsView = new Panel.Views.ColorControlsView({
      model: model
    });
    $('.side').append(colorControlsView.render().el);
    recentColorsView = new Panel.Views.RecentColorsView({
      collection: recentColors,
      model: model
    });
    $('.side').prepend(recentColorsView.render().el);
    paletteView = new Panel.Views.PaletteView({
      model: model
    });
    $('.middle').html(paletteView.render().el);
    tabView = new Panel.Views.TabView({
      model: model
    });
    tabView.on('selection', function(selection) {
      var view;
      view = (function() {
        switch (selection) {
          case 'schemas':
            return new Panel.Views.SchemaView({
              model: this.model
            });
          case 'blend':
            return new Panel.Views.BlendView({
              model: this.model
            });
          default:
            return new Panel.Views.RangeView({
              model: this.model,
              mode: selection
            });
        }
      }).call(this);
      return this.update(view.render().el);
    }, tabView);
    return $('.main').append(tabView.render().el);
  });

}).call(this);
