// Generated by CoffeeScript 1.6.1
(function() {

  chrome.devtools.panels.create('Colors', null, 'panels/color.html', null);

  onShown.addListener(function() {
    var backgroundPageConnection;
    backgroundPageConnection = chrome.runtime.connect();
    backgroundPageConnection.onMessage.addListener(function(message) {});
    alert(chrome.devtools.inspectedWindow.tabId);
    return chrome.runtime.sendMessage({
      tabId: chrome.devtools.inspectedWindow.tabId,
      scriptToInject: "js/injected_colors.js"
    });
  });

}).call(this);
