// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Panel.Views.PaletteView = (function(_super) {

    __extends(PaletteView, _super);

    function PaletteView() {
      return PaletteView.__super__.constructor.apply(this, arguments);
    }

    PaletteView.prototype.template = "<ul class=\"tabs\">\n  <li class=\"selected\">\n    <a href=\"#\">Page Colors</a>\n  </li>\n</ul>\n<a href=\"#\" class=\"fetch_colors\">Reload</a>\n<p class=\"palette_instructions\">Select color to modify on page</p>\n<div class=\"range_colors\"></div>";

    PaletteView.prototype.events = {
      "click .fetch_colors": "onFetchColorsClick"
    };

    PaletteView.prototype.initialize = function() {
      this.model.on('change:palette', this.render, this);
      this.model.on('change:syncColor', this.onSyncColorChange, this);
      return this.fetchPalette();
    };

    PaletteView.prototype.fetchPalette = function() {
      var port,
        _this = this;
      if (chrome.runtime != null) {
        port = chrome.runtime.connect();
        port.postMessage({
          label: 'fetch_palette'
        });
        return port.onMessage.addListener(function(msg) {
          return _this.model.set({
            palette: msg
          });
        });
      }
    };

    PaletteView.prototype.render = function() {
      this.$el.html(Mustache.render(this.template, _.extend({}, this.model.toJSON(), {
        amount: this.model.get('palette').length
      })));
      this.renderColors();
      return this;
    };

    PaletteView.prototype.renderColors = function() {
      var colorsView,
        _this = this;
      colorsView = new Panel.Views.ColorsView({
        model: this.model,
        colors: this.model.get('palette')
      });
      colorsView.on('select', function(color, $el) {
        _this.model.set({
          color: color,
          syncColor: color,
          rangeStart: color
        });
        colorsView.$('.selected').removeClass('selected');
        _this.$('.range_colors li').css({
          opacity: 0.2
        });
        $el.addClass('selected');
        return $el.parent().css({
          opacity: 1
        });
      });
      colorsView.on('unselect', function(color, $el) {
        _this.model.unset('syncColor');
        colorsView.$('.selected').removeClass('selected');
        return _this.$('.range_colors li').css({
          opacity: 1
        });
      });
      return this.$('.range_colors').html(colorsView.render().el);
    };

    PaletteView.prototype.onReloadClick = function(ev) {
      ev.preventDefault();
      this.model.set({
        palette: []
      });
      return this.fetchPalette();
    };

    PaletteView.prototype.onSyncColorChange = function() {
      if (this.model.get('syncColor') == null) {
        return $('.range_colors .selected').removeClass('selected');
      }
    };

    PaletteView.prototype.onFetchColorsClick = function(ev) {
      ev.preventDefault();
      return this.fetchPalette();
    };

    return PaletteView;

  })(Backbone.View);

}).call(this);
