// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Panel.Views.TabView = (function(_super) {

    __extends(TabView, _super);

    function TabView() {
      return TabView.__super__.constructor.apply(this, arguments);
    }

    TabView.prototype.template = "<div class=\"tab_header\">\n  <a href=\"#\" class=\"collapse\"></a>\n  <a href=\"#\" class=\"expand\" style=\"display: none;\"></a>\n  <ul class=\"tabs\">\n    <li class=\"selected\" data-tab=\"lighten\">\n      <a href=\"#\">Lighten</a>\n    </li>\n    <li data-tab=\"darken\">\n      <a href=\"#\">Darken</a>\n    </li>\n    <li data-tab=\"saturate\">\n      <a href=\"#\">Saturate</a>\n    </li>\n    <li data-tab=\"desaturate\">\n      <a href=\"#\">Desaturate</a>\n    </li>\n    <li data-tab=\"blend\">\n      <a href=\"#\">Blend</a>\n    </li>\n    <li data-tab=\"schemas\">\n      <a href=\"#\">Schemas</a>\n    </li>\n  </ul>\n</div>\n<div id=\"tab_content\" style=\"overflow: scroll\"></div>";

    TabView.prototype.events = {
      "click ul.tabs > li": "onItemClick",
      "click .collapse": "onCollapseClick",
      "click .expand": "onExpandClick"
    };

    TabView.prototype.render = function() {
      this.$el.html(Mustache.render(this.template));
      this.trigger('selection', this.model.get('tab'));
      this.model.on('change:pageColorsCollapsed', this.collapse, this);
      this.model.on('change:tab', this.loadTab, this);
      return this;
    };

    TabView.prototype.onItemClick = function(ev) {
      var $el;
      ev.preventDefault();
      $el = $(ev.currentTarget);
      this.model.set({
        tab: $el.data('tab')
      });
      return this.loadTab();
    };

    TabView.prototype.loadTab = function() {
      this.$('.selected').removeClass('selected');
      this.$("[data-tab='" + (this.model.get('tab')) + "']").addClass('selected');
      return this.trigger('selection', this.model.get('tab'));
    };

    TabView.prototype.update = function($el) {
      return this.$('#tab_content').html($el);
    };

    TabView.prototype.onCollapseClick = function(ev) {
      ev.preventDefault();
      this.model.unset('syncColor');
      this.model.set({
        pageColorsCollapsed: true
      });
      return this.collapse();
    };

    TabView.prototype.collapse = function() {
      this.$('.expand').show();
      this.$('.collapse').hide();
      return $('body').addClass('collapsed_page_colors');
    };

    TabView.prototype.onExpandClick = function(ev) {
      ev.preventDefault();
      this.model.set({
        pageColorsCollapsed: false
      });
      return this.expand();
    };

    TabView.prototype.expand = function() {
      this.$('.expand').hide();
      this.$('.collapse').show();
      return $('body').removeClass('collapsed_page_colors');
    };

    return TabView;

  })(Backbone.View);

}).call(this);
